# Generated by Django 3.1.7 on 2021-06-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summercampapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Program_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ProgramName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='summercampapp.program_management'),
        ),
        migrations.AlterField(
            model_name='program_management',
            name='TeachingMode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
