# Generated by Django 3.1.7 on 2021-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercampapp', '0002_auto_20210613_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ProgramName',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Program_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
